/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Dao.DAO_Laporan;
import java.text.SimpleDateFormat;
import service.service_laporan;

public class Laporan_BarangMasuk extends javax.swing.JPanel {
   private service_laporan servisLap = new DAO_Laporan();
//    private final int noColumnIndex = 0;
//    private final int noColumnWidth = 50;
    
    public Laporan_BarangMasuk(String id) {
        initComponents();
        lb_id.setText(id);
        pn_perTransaksi.setVisible(false);
        pn_perPeriode.setVisible(false);
        pn_perDistributor.setVisible(false);
        pn_perBulan.setVisible(false);
        btn_batal.setVisible(false);
        lb_id.setVisible(false);
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        mainPanel = new javax.swing.JPanel();
        Laporan = new javax.swing.JPanel();
        pn_pilihLaporan = new javax.swing.JPanel();
        cbx_laporan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        pn_perTransaksi = new javax.swing.JPanel();
        btn_printPertransaksi = new javax.swing.JButton();
        t_noTransaksi = new javax.swing.JTextField();
        btn_pilih = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pn_perPeriode = new javax.swing.JPanel();
        btn_printPerperiode = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        pn_perBulan = new javax.swing.JPanel();
        btn_printPerbulan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbx_bulan = new javax.swing.JComboBox<>();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        pn_perDistributor = new javax.swing.JPanel();
        btn_printDistributor = new javax.swing.JButton();
        t_idDistributor = new javax.swing.JTextField();
        btn_pilihDistributor = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pn_tampilLaporan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();

        jTextField8.setText("jTextField2");
        jTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        Laporan.setBackground(new java.awt.Color(255, 255, 255));
        Laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaporanMouseClicked(evt);
            }
        });

        pn_pilihLaporan.setBackground(new java.awt.Color(255, 255, 255));
        pn_pilihLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbx_laporan.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        cbx_laporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Jenis Laporan --", "Per Transaksi", "Per Distributor", "Per Periode", "Per Bulan" }));
        cbx_laporan.setBorder(null);
        cbx_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_laporanActionPerformed(evt);
            }
        });
        pn_pilihLaporan.add(cbx_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 284, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pilih Jenis Laporan");
        pn_pilihLaporan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 284, 22));

        btn_batal.setBackground(new java.awt.Color(255, 255, 153));
        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        btn_batal.setText("Kembali");
        btn_batal.setBorder(null);
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        pn_pilihLaporan.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 150, 40));

        pn_perTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        pn_perTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_printPertransaksi.setBackground(new java.awt.Color(51, 153, 255));
        btn_printPertransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_printPertransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_printPertransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/printer.png"))); // NOI18N
        btn_printPertransaksi.setText("Print");
        btn_printPertransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printPertransaksiActionPerformed(evt);
            }
        });

        t_noTransaksi.setText("No Transaksi");

        btn_pilih.setBackground(new java.awt.Color(51, 153, 255));
        btn_pilih.setForeground(new java.awt.Color(255, 255, 255));
        btn_pilih.setText("...");
        btn_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Laporan Per Transaksi");

        javax.swing.GroupLayout pn_perTransaksiLayout = new javax.swing.GroupLayout(pn_perTransaksi);
        pn_perTransaksi.setLayout(pn_perTransaksiLayout);
        pn_perTransaksiLayout.setHorizontalGroup(
            pn_perTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_perTransaksiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_perTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_printPertransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_noTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pilih, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_perTransaksiLayout.setVerticalGroup(
            pn_perTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_perTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_perTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_pilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_noTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_printPertransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pn_pilihLaporan.add(pn_perTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 284, -1));

        pn_perPeriode.setBackground(new java.awt.Color(255, 255, 255));
        pn_perPeriode.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_printPerperiode.setBackground(new java.awt.Color(51, 153, 255));
        btn_printPerperiode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_printPerperiode.setForeground(new java.awt.Color(255, 255, 255));
        btn_printPerperiode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/printer.png"))); // NOI18N
        btn_printPerperiode.setText("Print");
        btn_printPerperiode.setBorder(null);
        btn_printPerperiode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printPerperiodeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dari Tanggal");

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sampai Tanggal");

        javax.swing.GroupLayout pn_perPeriodeLayout = new javax.swing.GroupLayout(pn_perPeriode);
        pn_perPeriode.setLayout(pn_perPeriodeLayout);
        pn_perPeriodeLayout.setHorizontalGroup(
            pn_perPeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_perPeriodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_perPeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_perPeriodeLayout.createSequentialGroup()
                        .addGroup(pn_perPeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_perPeriodeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
            .addGroup(pn_perPeriodeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_printPerperiode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_perPeriodeLayout.setVerticalGroup(
            pn_perPeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_perPeriodeLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_printPerperiode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_pilihLaporan.add(pn_perPeriode, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 284, -1));

        pn_perBulan.setBackground(new java.awt.Color(255, 255, 255));
        pn_perBulan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_printPerbulan.setBackground(new java.awt.Color(51, 153, 255));
        btn_printPerbulan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_printPerbulan.setForeground(new java.awt.Color(255, 255, 255));
        btn_printPerbulan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/printer.png"))); // NOI18N
        btn_printPerbulan.setText("Print");
        btn_printPerbulan.setBorder(null);
        btn_printPerbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printPerbulanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bulan");

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tahun");

        cbx_bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Bulan --", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        cbx_bulan.setBorder(null);

        javax.swing.GroupLayout pn_perBulanLayout = new javax.swing.GroupLayout(pn_perBulan);
        pn_perBulan.setLayout(pn_perBulanLayout);
        pn_perBulanLayout.setHorizontalGroup(
            pn_perBulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_perBulanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_perBulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_perBulanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbx_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_perBulanLayout.createSequentialGroup()
                        .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pn_perBulanLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_printPerbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_perBulanLayout.setVerticalGroup(
            pn_perBulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_perBulanLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_printPerbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_pilihLaporan.add(pn_perBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 284, -1));

        pn_perDistributor.setBackground(new java.awt.Color(255, 255, 255));
        pn_perDistributor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_printDistributor.setBackground(new java.awt.Color(51, 153, 255));
        btn_printDistributor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_printDistributor.setForeground(new java.awt.Color(255, 255, 255));
        btn_printDistributor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/printer.png"))); // NOI18N
        btn_printDistributor.setText("Print");
        btn_printDistributor.setBorder(null);
        btn_printDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printDistributorActionPerformed(evt);
            }
        });

        t_idDistributor.setText("Distributor");

        btn_pilihDistributor.setBackground(new java.awt.Color(51, 153, 255));
        btn_pilihDistributor.setForeground(new java.awt.Color(255, 255, 255));
        btn_pilihDistributor.setText("...");
        btn_pilihDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihDistributorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Laporan Distributor");

        javax.swing.GroupLayout pn_perDistributorLayout = new javax.swing.GroupLayout(pn_perDistributor);
        pn_perDistributor.setLayout(pn_perDistributorLayout);
        pn_perDistributorLayout.setHorizontalGroup(
            pn_perDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_perDistributorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_perDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_printDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_idDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pilihDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_perDistributorLayout.setVerticalGroup(
            pn_perDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_perDistributorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(pn_perDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_idDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pilihDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_printDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pn_pilihLaporan.add(pn_perDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 284, -1));

        pn_tampilLaporan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_tampilLaporanLayout = new javax.swing.GroupLayout(pn_tampilLaporan);
        pn_tampilLaporan.setLayout(pn_tampilLaporanLayout);
        pn_tampilLaporanLayout.setHorizontalGroup(
            pn_tampilLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        pn_tampilLaporanLayout.setVerticalGroup(
            pn_tampilLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laporan Barang Masuk");

        lb_id.setForeground(new java.awt.Color(255, 255, 255));
        lb_id.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_id.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_id)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout LaporanLayout = new javax.swing.GroupLayout(Laporan);
        Laporan.setLayout(LaporanLayout);
        LaporanLayout.setHorizontalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_pilihLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_tampilLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LaporanLayout.setVerticalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_pilihLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(pn_tampilLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(Laporan, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        mainPanel.removeAll();
        String id = lb_id.getText();
        mainPanel.add(new Laporan_BarangMasuk(id));
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void LaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanMouseClicked
        
    }//GEN-LAST:event_LaporanMouseClicked

    private void btn_printPertransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printPertransaksiActionPerformed
        pn_tampilLaporan.removeAll();
        String no = t_noTransaksi.getText();
        servisLap.lapBarangMasukPerTransaksi(pn_tampilLaporan,no);
    }//GEN-LAST:event_btn_printPertransaksiActionPerformed

    private void cbx_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_laporanActionPerformed
        if(cbx_laporan.getSelectedItem() == "-- Pilih Jenis Laporan --"){
            btn_batal.setVisible(false);
            pn_perTransaksi.setVisible(false);
            pn_perPeriode.setVisible(false);
            pn_perBulan.setVisible(false);
            pn_perDistributor.setVisible(false);
        }else if(cbx_laporan.getSelectedItem() == "Per Transaksi"){
            btn_batal.setVisible(true);
            pn_perTransaksi.setVisible(true);
            pn_perPeriode.setVisible(false);
            pn_perBulan.setVisible(false);
            pn_perDistributor.setVisible(false);
        }else if (cbx_laporan.getSelectedItem() == "Per Periode"){
            btn_batal.setVisible(true);
            pn_perTransaksi.setVisible(false);
            pn_perPeriode.setVisible(true);
            pn_perBulan.setVisible(false);
            pn_perDistributor.setVisible(false);
        }else if (cbx_laporan.getSelectedItem() == "Per Bulan"){
            btn_batal.setVisible(true);
            pn_perTransaksi.setVisible(false);
            pn_perPeriode.setVisible(false);
            pn_perBulan.setVisible(true);
            pn_perDistributor.setVisible(false);
        }else if (cbx_laporan.getSelectedItem() == "Per Distributor"){
            btn_batal.setVisible(true);
            pn_perTransaksi.setVisible(false);
            pn_perPeriode.setVisible(false);
            pn_perBulan.setVisible(false);
            pn_perDistributor.setVisible(true);
        }
    }//GEN-LAST:event_cbx_laporanActionPerformed

    private void btn_printPerperiodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printPerperiodeActionPerformed
        pn_tampilLaporan.removeAll();
        
        String tgl = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tgl);
        
        String tgl1 = String.valueOf(fm.format(jDateChooser1.getDate()));
        String tgl2 = String.valueOf(fm.format(jDateChooser2.getDate()));
        
        servisLap.lapBarangMasukPerPeriode(pn_tampilLaporan,tgl1,tgl2);
    }//GEN-LAST:event_btn_printPerperiodeActionPerformed

    private void btn_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihActionPerformed
        boolean closable = true;
        Data_BarangMasuk dataBarMas = new Data_BarangMasuk(null, closable);
        dataBarMas.setVisible(true);
        
        t_noTransaksi.setText(dataBarMas.BarMas.getNo_masuk());
    }//GEN-LAST:event_btn_pilihActionPerformed

    private void btn_printPerbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printPerbulanActionPerformed
        pn_tampilLaporan.removeAll();
        
        String bulan = cbx_bulan.getSelectedItem().toString();
        int tahun = jYearChooser1.getYear();
        
        servisLap.lapBarangMasukPerBulan(pn_tampilLaporan, bulan, tahun);
    }//GEN-LAST:event_btn_printPerbulanActionPerformed

    private void btn_printDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printDistributorActionPerformed
        pn_tampilLaporan.removeAll();
        String no = t_idDistributor.getText();
        servisLap.lapBarangMasukPerDistributor(pn_tampilLaporan,no);
    }//GEN-LAST:event_btn_printDistributorActionPerformed

    private void btn_pilihDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihDistributorActionPerformed
        boolean closable = true;
        Data_distributor dataDistributor = new Data_distributor(null, closable);
        dataDistributor.setVisible(true);
        
        t_idDistributor.setText(dataDistributor.dist.getId_distributor());
    }//GEN-LAST:event_btn_pilihDistributorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Laporan;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_pilih;
    private javax.swing.JButton btn_pilihDistributor;
    private javax.swing.JButton btn_printDistributor;
    private javax.swing.JButton btn_printPerbulan;
    private javax.swing.JButton btn_printPerperiode;
    private javax.swing.JButton btn_printPertransaksi;
    private javax.swing.JComboBox<String> cbx_bulan;
    private javax.swing.JComboBox<String> cbx_laporan;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField8;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel lb_id;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_perBulan;
    private javax.swing.JPanel pn_perDistributor;
    private javax.swing.JPanel pn_perPeriode;
    private javax.swing.JPanel pn_perTransaksi;
    private javax.swing.JPanel pn_pilihLaporan;
    private javax.swing.JPanel pn_tampilLaporan;
    private javax.swing.JTextField t_idDistributor;
    private javax.swing.JTextField t_noTransaksi;
    // End of variables declaration//GEN-END:variables



}
