/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Dao.DAO_Barang;
import TableModel.TableMod_barang;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.model_barang;
import model.model_jenisBarang;
import service.service_barang;

/**
 *
 * @author alams
 */
public class Master_Barang extends javax.swing.JPanel {
    
    private service_barang servis = new DAO_Barang();
    private TableMod_barang tblModel = new TableMod_barang();

    /**
     * Creates new form Master_Barang
     */
    public Master_Barang() {
        initComponents();
        
        tbl_barang.setModel(tblModel);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        t_cari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tambahData = new javax.swing.JPanel();
        btn_tambah2 = new javax.swing.JButton();
        btn_batal2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        t_kodeBarang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_kodeJenisBarang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_jenisBarang = new javax.swing.JButton();
        t_namaJenisBarang = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t_namaBarang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbx_satuan = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        t_hargaBarang = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t_stok = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jTextField8.setText("jTextField2");
        jTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(255, 255, 255));

        btn_tambah.setBackground(new java.awt.Color(153, 255, 153));
        btn_tambah.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/plus.png"))); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.setBorder(null);
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(255, 51, 51));
        btn_hapus.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.setBorder(null);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(255, 255, 153));
        btn_batal.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close.png"))); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.setBorder(null);
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tbl_barang.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_barang.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_barang.setIntercellSpacing(new java.awt.Dimension(5, 0));
        tbl_barang.setName(""); // NOI18N
        tbl_barang.setRowHeight(25);
        tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_barang);

        t_cari.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        t_cari.setText(" Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_cariFocusLost(evt);
            }
        });
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t_cariMouseExited(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Data Barang");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(tampilData, "card2");

        tambahData.setBackground(new java.awt.Color(255, 255, 255));

        btn_tambah2.setBackground(new java.awt.Color(153, 255, 153));
        btn_tambah2.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btn_tambah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save.png"))); // NOI18N
        btn_tambah2.setText("Tambah");
        btn_tambah2.setBorder(null);
        btn_tambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah2ActionPerformed(evt);
            }
        });

        btn_batal2.setBackground(new java.awt.Color(255, 255, 153));
        btn_batal2.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btn_batal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close.png"))); // NOI18N
        btn_batal2.setText("Batal");
        btn_batal2.setBorder(null);
        btn_batal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel10.setText("Kode Barang");

        t_kodeBarang.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        t_kodeBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        t_kodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kodeBarangActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel11.setText("Nama Jenis Barang");

        t_kodeJenisBarang.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        t_kodeJenisBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        t_kodeJenisBarang.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel12.setText("Jenis Barang");

        btn_jenisBarang.setBackground(new java.awt.Color(51, 153, 255));
        btn_jenisBarang.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btn_jenisBarang.setForeground(new java.awt.Color(255, 255, 255));
        btn_jenisBarang.setText("Pilih");
        btn_jenisBarang.setBorder(null);
        btn_jenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jenisBarangActionPerformed(evt);
            }
        });

        t_namaJenisBarang.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        t_namaJenisBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        t_namaJenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaJenisBarangActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel13.setText("Nama Barang");

        t_namaBarang.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        t_namaBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        t_namaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaBarangActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel14.setText("Satuan");

        cbx_satuan.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        cbx_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Jenis Satuan -", "Pcs", "Buah", "Pack", "Dos", " " }));
        cbx_satuan.setBorder(null);

        jLabel15.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel15.setText("Harga");

        t_hargaBarang.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        t_hargaBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        t_hargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_hargaBarangActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel16.setText("Stok");

        t_stok.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        t_stok.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        t_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_stokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(t_stok)
                    .addComponent(t_hargaBarang, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_namaBarang, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_namaJenisBarang, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_kodeJenisBarang)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_kodeBarang)
                    .addComponent(cbx_satuan, javax.swing.GroupLayout.Alignment.LEADING, 0, 397, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_jenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_kodeJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_jenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_hargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   Tambah Data Barang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_tambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahData, "card3");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void t_kodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodeBarangActionPerformed

    private void t_namaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaBarangActionPerformed

    private void t_hargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_hargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_hargaBarangActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void t_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_stokActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
//        mengganti tampilan
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
//        mengubah tampilan ke tambah data
        mainPanel.add(tambahData);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        btn_tambah2.setText("Simpan"); //mengubah tombol tambah menjadi simpan pada panel tambah data
        btn_jenisBarang.setEnabled(true); //set true agar tombol janis barang bisa diklik
        t_kodeBarang.setText(servis.nomor());//melakukan penomoran otomatis melalui DAO_Barang
        t_kodeJenisBarang.setEnabled(false);
        t_kodeBarang.setEnabled(false);
        
        if (btn_tambah.getText().equals("Ubah"))
        {
            dataTabel();
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_jenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jenisBarangActionPerformed
        boolean closable = true;
        Data_jenisBarang djb = new Data_jenisBarang(null, closable);
        djb.setVisible(true);
        
        t_kodeJenisBarang.setText(djb.jb.getKode_jenis());
        t_namaJenisBarang.setText(djb.jb.getNama_jenis());
       
        t_kodeBarang.setEnabled(false);
        t_namaJenisBarang.setEnabled(false);
        t_namaBarang.requestFocus();
        aktif();
    }//GEN-LAST:event_btn_jenisBarangActionPerformed

    private void btn_tambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah2ActionPerformed
        if (btn_tambah2.getText().equals("Tambah")){
            btn_tambah2.setText("Simpan");
            t_kodeBarang.setText(servis.nomor());
            
        }else if (btn_tambah2.getText().equals("Simpan")){
            simpanData();
            
        }else if (btn_tambah2.getText().equals("Perbarui")){
            PerbaruiData();
        }
    }//GEN-LAST:event_btn_tambah2ActionPerformed

    private void t_namaJenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaJenisBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaJenisBarangActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked
        ImageIcon change = new ImageIcon(getClass().getResource("/Icon/change.png"));
        if (btn_tambah.getText().equals("Tambah")){
            btn_tambah.setText("Ubah");
            btn_tambah.setIcon(change);
        }
        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);

//try {
//        ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Icon/change.png"));
//        if (btn_tambah.getText().equals("Tambah")) {
//            btn_tambah.setText("Ubah");
//            btn_tambah.setIcon(changeIcon);
//        }
//        btn_hapus.setVisible(true);
//        btn_batal.setVisible(true);
//    } catch (Exception e) {
//        e.printStackTrace();
//    }
    }//GEN-LAST:event_tbl_barangMouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal2ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batal2ActionPerformed

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void t_cariMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariMouseExited

    private void t_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusLost
        String cari = t_cari.getText();
        if (cari.equals("")|| cari.equals(" Pencarian")){
            t_cari.setText(" Pencarian");
        }
    }//GEN-LAST:event_t_cariFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal2;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_jenisBarang;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tambah2;
    private javax.swing.JComboBox<String> cbx_satuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_hargaBarang;
    private javax.swing.JTextField t_kodeBarang;
    private javax.swing.JTextField t_kodeJenisBarang;
    private javax.swing.JTextField t_namaBarang;
    private javax.swing.JTextField t_namaJenisBarang;
    private javax.swing.JTextField t_stok;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    private javax.swing.JTable tbl_barang;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
       btn_hapus.setVisible(false);
       btn_batal.setVisible(false);
       List <model_barang> list = servis.getData();
       tblModel.setData(list);
    }

    private void simpanData() {
        if (validasiInput ()== true){
            String kode_barang          = t_kodeBarang.getText();
            String kode_jenis           = t_kodeJenisBarang.getText();
            String nama_jenisBarang     = t_namaJenisBarang.getText();
            String nama_barang          = t_namaBarang.getText();
            String satuan               = cbx_satuan.getSelectedItem().toString();
            Long harga                  = Long.parseLong(t_hargaBarang.getText());
            int stok                    = Integer.parseInt(t_stok.getText());
            
            model_barang brg = new model_barang();
            model_jenisBarang jbr = new model_jenisBarang();
            
            brg.setKode_barang(kode_barang);
            jbr.setKode_jenis(kode_jenis);
            jbr.setNama_jenis(nama_jenisBarang);
            brg.setNama_barang(nama_barang);
            brg.setSatuan(satuan);
            brg.setHarga(harga);
            brg.setStok(stok);
            
            brg.setJenis_barang(jbr);
            
            servis.tambahData(brg);
            tblModel.tambahData(brg);
            loadData();
            resetForm();
            tampilPanel();
            btn_tambah2.setText("Tambah");
        }
    }
    
    
    private boolean validasiInput(){
        boolean valid = false;
        if(t_kodeBarang.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Kode Barang tidak boleh kosong!");
        }else if (t_kodeJenisBarang.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Kode Jenis Barang tidak boleh kosong!");
        }else if (t_namaBarang.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Barang tidak boleh kosong!");
        }else if (t_namaJenisBarang.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Jenis Barang tidak boleh kosong!");
        }else if (cbx_satuan.getSelectedItem().equals(null)){
            JOptionPane.showMessageDialog(null, "Satuan tidak boleh kosong!");
        }else if (t_hargaBarang.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga Barang tidak boleh kosong!");
        }else if (t_stok.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Stok Barang tidak boleh kosong!");
        }else{
            valid = true;
        }
        return valid;
    }

    private void resetForm() {
        btn_tambah.requestFocus();
        btn_tambah.setText("Tambah");
        t_kodeBarang.setText("");
        t_kodeJenisBarang.setText("");
        t_namaJenisBarang.setText("");
        t_namaBarang.setText("");
        cbx_satuan.setSelectedItem(0);
        t_hargaBarang.setText("");
        t_stok.setText("");
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Master_Barang());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void dataTabel() {
        tampilData.setVisible(false);
        tambahData.setVisible(true);
        
        int row = tbl_barang.getSelectedRow();
        jLabel2.setText("Perbarui Data Barang");
        
        t_kodeBarang.setEnabled(false);
        t_kodeJenisBarang.setEnabled(true);
        t_namaJenisBarang.setEnabled(true);
        
        t_kodeBarang.setText        (tbl_barang.getModel().getValueAt(row, 1).toString());
        t_kodeJenisBarang.setText   (tbl_barang.getModel().getValueAt(row, 2).toString());
        t_namaJenisBarang.setText   (tbl_barang.getModel().getValueAt(row, 3).toString());
        t_namaBarang.setText        (tbl_barang.getModel().getValueAt(row, 4).toString());
        cbx_satuan.setSelectedItem  (tbl_barang.getModel().getValueAt(row, 5).toString());
        t_hargaBarang.setText       (tbl_barang.getModel().getValueAt(row, 6).toString());
        t_stok.setText              (tbl_barang.getModel().getValueAt(row, 7).toString());
        
        aktif();
        btn_tambah2.setText("Perbarui");
        btn_batal.setVisible(true);
    }

    private void aktif() {
        t_namaBarang.setEnabled(true);
        cbx_satuan.setEnabled(true);
        t_hargaBarang.setEnabled(true);
        t_stok.setEnabled(true);
    }

    private void PerbaruiData() {
        int index = tbl_barang.getSelectedRow();
        if (index != -1){
            model_barang mobar = tblModel.getData(tbl_barang.convertRowIndexToModel(index));
            
            if (validasiInput() == true){
                String kode_barang = t_kodeBarang.getText();
                String kode_jenis = t_kodeJenisBarang.getText();
                //String nama_jenis = t_namaJenisBarang.getText();
                String nama_barang = t_namaBarang.getText();
                String satuan = cbx_satuan.getSelectedItem().toString();
                Long harga = Long.parseLong(t_hargaBarang.getText());
                int stok = Integer.parseInt(t_stok.getText());
                
                model_barang brg = new model_barang();
                model_jenisBarang jbr = new model_jenisBarang();
                
                jbr.setKode_jenis(kode_jenis);
                //jbr.setNama_jenis(nama_jenis);
                brg.setKode_barang(kode_barang);
                brg.setNama_barang(nama_barang);
                brg.setSatuan(satuan);
                brg.setHarga(harga);
                brg.setStok(stok);
                
                brg.setJenis_barang(jbr);
                
                servis.perbaruiData(brg);
                tblModel.perbaruiData(index, brg);
                loadData();
                resetForm();
                tampilPanel();
            }
        }
    }

    private void hapusData() {
        int index = tbl_barang.getSelectedRow();
        if (index != -1){
            model_barang brg = tblModel.getData(tbl_barang.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data?","Konfirmasi",JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                servis.hapusData(brg);
                tblModel.hapusData(index);
                loadData();
                resetForm();
            }
        }else {
            JOptionPane.showMessageDialog(null, "Pilih record yang akan dihapus!");
        }
    }

    private void pencarian() {
        List<model_barang> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);
    }
}
